{-|
Module      : Control.Effect.Internal.Runner
Description : Runners do initialisation/finalisation work before/after handling operations
License     : BSD-3-Clause
Maintainer  : Nicolas Wu, Zhixuan Yang
Stability   : experimental

In @effective@, a handler is pair of an algebra transformer and a runner. The
algebra transformer is responsible for handling effectful operations while a
runner does initialisation or finalisation work for the handler. For example,
the runner of a handler of mutable state can initialise the state by reading
from standard IO.
-}
{-# LANGUAGE ImpredicativeTypes, QuantifiedConstraints, UndecidableInstances #-}
{-# LANGUAGE UndecidableSuperClasses, MonoLocalBinds, LambdaCase, BlockArguments #-}
{-# LANGUAGE PartialTypeSignatures, MagicHash #-}
{-# OPTIONS_GHC -Wno-partial-type-signatures #-}

module Control.Effect.Internal.Runner where

import Data.List.Kind
import Data.Kind

import Control.Effect.Internal.Algebra
import Control.Effect.Internal.AlgTrans.Type
import Control.Effect.Internal.Forward
import Language.Haskell.TH hiding (Type)
import Language.Haskell.TH.Syntax (TExp (..))

-- * The primitive types for modular effect handlers

-- | Running a computation @ts m a@, resulting in a value @m b@
type Runner
  :: [Effect]                             -- ^ oeffs : output effects
  -> [(Type -> Type) -> (Type -> Type)]   -- ^ ts    : carrier transformer
  -> Type                                 -- ^ a     : input type
  -> Type                                 -- ^ b     : output type
  -> ((Type -> Type) -> Constraint)       -- ^ cs    : carrier constraint
  -> Type
newtype Runner oeffs ts a b cs = Runner {
  getR :: forall m . cs m => Algebra oeffs m -> Apply ts m a -> m b }

type RunnerC
  :: [Effect]                             -- ^ oeffs : output effects
  -> [(Type -> Type) -> (Type -> Type)]   -- ^ ts    : carrier transformer
  -> Type                                 -- ^ a     : input type
  -> Type                                 -- ^ b     : output type
  -> ((Type -> Type) -> Constraint)       -- ^ cs    : carrier constraint
  -> Type
newtype RunnerC oeffs ts a b cs = RunnerC {
  getRC :: forall m . cs m => AlgebraC oeffs m -> CodeQ (Apply ts m a -> m b) }

-- * Building runners

-- | Runners that don't need any output effects.
{-# INLINE runner' #-}
runner' :: (forall m x . cs m => Apply ts m a -> m b) -> Runner oeffs ts a b cs
runner' run = Runner (\(_ :: Algebra _ m) -> run @m)

-- | Trivial runner that does nothing.
{-# INLINE idRunner #-}
idRunner :: forall effs cs a.  Runner effs '[] a a cs
idRunner = Runner \_ x -> x

type CompR# ts1 ts2 =
   ( forall m. Assoc ts1 ts2 m :: Constraint )

-- | @compR at r1 r2@ is the runner that executes @r1@ and then @r2@. An algebra
-- transformer @at@ is needed to transform the effects @oeffs2@ to the effects @oeffs1@
-- needed by @r1@.
{-# INLINE compR #-}
compR
  :: forall oeffs1 oeffs2 ts1 ts2 a1 a2 a3 cs1 cs2.
     CompR# ts1 ts2
  => AlgTrans oeffs1 oeffs2 ts2 cs2
     -- ^ Algebra transformer
  -> Runner oeffs1 ts1 a1 a2 cs1
     -- ^ The first runner
  -> Runner oeffs2 ts2 a2 a3 cs2
     -- ^ The second runner
  -> Runner oeffs2 (ts1 :++ ts2)
                   a1 a3
                   (CompC ts2 cs1 cs2)
compR at r1 r2 = Runner \(oalg :: Algebra _ m) ->
    getR r2 oalg .  getR r1 (getAT at @m oalg)

type FuseR# effs2 oeffs1 oeffs2 ts1 ts2 =
  ( Members (oeffs1 :\\ effs2) ((oeffs1 :\\ effs2) `Union` oeffs2)
  , Members oeffs2 ((oeffs1 :\\ effs2) `Union` oeffs2)
  , CompR# ts1 ts2 )

-- | @fuseR at2 r1 r2@ is similar to @compR at2 r1 r2@ except that the effects generated by
-- @r1@ are handled by @at2@.
{-# INLINE fuseR #-}
fuseR
  :: forall effs2 oeffs1 oeffs2 ts1 ts2 a1 a2 a3 cs1 cs2.
     ( ForwardsC cs2 (oeffs1 :\\ effs2) ts2
     , Members oeffs1 ((oeffs1 :\\ effs2) :++ effs2)
     , FuseR# effs2 oeffs1 oeffs2 ts1 ts2 )
  => AlgTrans effs2 oeffs2 ts2 cs2
     -- ^ The algebra transformer
  -> Runner oeffs1 ts1 a1 a2 cs1
     -- ^ The first runner
  -> Runner oeffs2 ts2 a2 a3 cs2
     -- ^ The second runner
  -> Runner ((oeffs1 :\\ effs2) `Union` oeffs2)
            (ts1 :++ ts2)
            a1 a3
            (CompC ts2 cs1 cs2)
fuseR at2 r1 r2 = Runner \(oalg :: Algebra _ m)  ->
      getR r2 (weakenAlg oalg)
    . getR r1 (weakenAlg @oeffs1 @((oeffs1 :\\ effs2) :++ effs2) $
        appendAlg @(oeffs1 :\\ effs2) @effs2
          (getAT (fwds @(oeffs1 :\\ effs2) @(ts2))
            (weakenAlg @(oeffs1 :\\ effs2) @_ oalg))
          (getAT at2 (weakenAlg @oeffs2 @_ oalg)))

-- | A variant of `fuseR` that concatenates algebras rather than taking their
-- union. Concatenation is faster than union for most underlying data
-- structures of algebras, but it should only be used when @oeffs1@ and @oeffs2@
-- have no intersection to avoid unexpected behaviour.
{-# INLINE fuseAppR #-}
fuseAppR
  :: forall effs2 oeffs1 oeffs2 ts1 ts2 a1 a2 a3 cs1 cs2.
     ( ForwardsC cs2 oeffs1 ts2
     , KnownEffs oeffs1
     , forall m. Assoc ts1 ts2 m )
  => AlgTrans effs2 oeffs2 ts2 cs2
     -- ^ The algebra transformer
  -> Runner oeffs1 ts1 a1 a2 cs1
     -- ^ The first runner
  -> Runner oeffs2 ts2 a2 a3 cs2
     -- ^ The second runner
  -> Runner (oeffs1 :++ oeffs2)
            (ts1 :++ ts2)
            a1 a3
            (CompC ts2 cs1 cs2)
fuseAppR at2 r1 r2 = Runner \(oalg :: Algebra (oeffs1 :++ oeffs2) m)  ->
  let (oalg1, oalg2) = splitAlg @oeffs1 @oeffs2 oalg
  in getR r2 oalg2 . getR r1 (getAT (fwds @(oeffs1) @ts2) oalg1)

-- | Staged version of `fuseR`.
fuseRC
  :: forall effs2 oeffs1 oeffs2 ts1 ts2 a1 a2 a3 cs1 cs2.
     ( ForwardsC cs2 (oeffs1 :\\ effs2) ts2
     , Members oeffs1 ((oeffs1 :\\ effs2) :++ effs2)
     , FuseR# effs2 oeffs1 oeffs2 ts1 ts2 )
  => AlgTransC effs2 oeffs2 ts2 cs2
     -- ^ The staged algebra transformer
  -> RunnerC oeffs1 ts1 a1 a2 cs1
     -- ^ The first staged runner
  -> RunnerC oeffs2 ts2 a2 a3 cs2
     -- ^ The second staged runner
  -> RunnerC ((oeffs1 :\\ effs2) `Union` oeffs2)
             (ts1 :++ ts2)
             a1 a3
             (CompC ts2 cs1 cs2)
-- | In Template Haskell we can cheat a bit by examining the runners, and
-- if one of them is the identity function, then we do nothing.
fuseRC at2 r1 r2 = RunnerC \(oalg :: AlgebraC _ m)  ->
    [|| $$(getRC r2 (weakenAlgC oalg)) ||]
    `circCode`
    [|| $$(getRC r1 (weakenAlgC @oeffs1 @((oeffs1 :\\ effs2) :++ effs2) $
        appendAlgC @(oeffs1 :\\ effs2) @effs2
          (getATC (fwdsC @(oeffs1 :\\ effs2) @(ts2))
            (weakenAlgC @(oeffs1 :\\ effs2) @_ oalg))
          (getATC at2 (weakenAlgC @oeffs2 @_ oalg))))
    ||]

-- | Compose the code of two functions such that @id . f@ and @f . id@ compute
-- to @f@. This is achieved using the unsafe, untyped Template Haskell API. There should
-- be a safer way to do this, but for now this version is sufficient.
circCode :: CodeQ (b -> c) -> CodeQ (a -> b) -> CodeQ (a -> c)
circCode (Code qG) (Code qF) = Code $
  do (TExp f) <- qF
     (TExp g) <- qG
     idCode <- [| Prelude.id |]
     if f == idCode
       then return (TExp g)
       else if g == idCode
             then return (TExp f)
             else fmap TExp [| $(pure g) . $(pure f)|]

-- | Staged version of `fuseAppR`.
fuseAppRC
  :: forall effs2 oeffs1 oeffs2 ts1 ts2 a1 a2 a3 cs1 cs2.
     ( ForwardsC cs2 oeffs1 ts2, forall m. Assoc ts1 ts2 m, KnownEffs oeffs1 )
  => RunnerC oeffs1 ts1 a1 a2 cs1
     -- ^ The first staged runner
  -> RunnerC oeffs2 ts2 a2 a3 cs2
     -- ^ The second staged runner
  -> RunnerC (oeffs1  :++ oeffs2)
             (ts1 :++ ts2)
             a1 a3
             (CompC ts2 cs1 cs2)
fuseAppRC r1 r2 = RunnerC \(oalg :: AlgebraC (oeffs1 :++ oeffs2) m)  ->
  let (oalg1, oalg2) = splitAlgC @oeffs1 @oeffs2 oalg
  in [|| $$(getRC r2 oalg2) ||]
     `circCode`
     [|| $$(getRC r1 (getATC (fwdsC @(oeffs1) @ts2) oalg1)) ||]

type PassR# effs2 oeffs1 oeffs2 ts1 ts2 a1 a2 a3 =
   ( Members oeffs1 (oeffs1 `Union` oeffs2)
   , Members oeffs2 (oeffs1 `Union` oeffs2)
   , CompR# ts1 ts2)

-- | @passR r1 r2@ runs @r1@ and @r2@ in sequence, but unlike @fuseR at2 r1 r2@,
-- in @passR r1 r2@, the effects produced by @r1@ are not handled by @at2@.
{-# INLINE passR #-}
passR
  :: forall effs2 oeffs1 oeffs2 ts1 ts2 a1 a2 a3 cs1 cs2.
     ( ForwardsC cs2 oeffs1 ts2
     , PassR# effs2 oeffs1 oeffs2 ts1 ts2 a1 a2 a3 )
  => Runner oeffs1 ts1 a1 a2 cs1
     -- ^ The first runner
  -> Runner oeffs2 ts2 a2 a3 cs2
     -- ^ The second runner
  -> Runner (oeffs1 `Union` oeffs2)
            (ts1 :++ ts2)
            a1 a3
            (CompC ts2 cs1 cs2)
passR r1 r2 = Runner \(oalg :: Algebra _ m)  ->
      getR r2 (weakenAlg oalg)
    . getR r1 (getAT (fwds @oeffs1 @ts2) (weakenAlg oalg))

-- | Weaken the effects and the constraints of a runner.
{-# INLINE weakenR #-}
weakenR
  :: forall cs' effs' cs effs ts a b.
     ( forall m. cs' m => cs m, Members effs effs' )
  => Runner effs  ts a b cs     -- ^ Runner to weaken
  -> Runner effs' ts a b cs'
weakenR r1 = Runner \oalg -> getR r1 (weakenAlg oalg)

-- | Weaken the effects of a runner.
{-# INLINE weakenREffs #-}
weakenREffs
  :: forall effs' cs effs ts a b.
     (Members effs effs')
  => Runner effs ts a b cs     -- ^ Runner to weaken
  -> Runner effs' ts a b cs
weakenREffs r1 = Runner \oalg -> getR r1 (weakenAlg oalg)

-- | Weaken the constraint of a runner.
{-# INLINE weakenRCS #-}
weakenRCS
  :: forall cs' cs effs ts a b.
     (forall m. cs' m => cs m)
  => Runner effs ts a b cs     -- ^ Runner whose constraint is weakened
  -> Runner effs ts a b cs'
weakenRCS r1 = Runner \oalg -> getR r1 oalg

{-# INLINE weakenRCSMonad #-}
-- | Drop a @'CompC' ts2 Monad Monad@ carrier constraint down to plain @Monad@.
--
-- This is the @cs = 'CompC' ts2 Monad Monad@, @cs' = Monad@ specialisation of
-- 'weakenRCS'. As of GHC 9.14, callers such as 'Control.Effect.Internal.Handler.comp'
-- cannot use 'weakenRCS' directly: with /two/ quantified givens
-- @forall m. Monad m => MonadApply ts1 m@ and @forall m. Monad m => MonadApply ts2 m@
-- in scope, the solver refuses to choose between them when discharging
-- @Monad ('Apply' ts2 m)@, because the superclass heads mention the
-- non-injective family 'Apply'. This wrapper narrows the context to the
-- single relevant quantified given, making the choice unambiguous.
weakenRCSMonad
  :: forall ts2 effs ts a b.
     (forall m. Monad m => MonadApply ts2 m)
  => Runner effs ts a b (CompC ts2 Monad Monad)
     -- ^ Runner to weaken
  -> Runner effs ts a b Monad
weakenRCSMonad = weakenRCS

-- | Weaken the constraint of a staged runner.
weakenRCSC
  :: forall cs' cs effs ts a b.
     (forall m. cs' m => cs m)
  => RunnerC effs ts a b cs     -- ^ Staged runner whose constraint is weakened
  -> RunnerC effs ts a b cs'
weakenRCSC r1 = RunnerC \oalg -> getRC r1 oalg

-- | A special case of @weakenRCSC@ that gives the type checker more hints.
weakenRCSCMonad
  :: forall ts2 effs ts a b.
     (forall m. Monad m => MonadApply ts2 m)
  => RunnerC effs ts a b (CompC ts2 Monad Monad)
     -- ^ Runner to weaken
  -> RunnerC effs ts a b Monad
weakenRCSCMonad = weakenRCSC